import React from 'react';
import ReactMarkdown from 'react-markdown';
import { ArrowLeft, Printer, Sparkles, CheckCircle2, ChevronRight, Target, Lightbulb, BookOpen, Download, Share2 } from 'lucide-react';

interface ReportViewProps {
  markdown: string;
  onReset: () => void;
}

const ReportView: React.FC<ReportViewProps> = ({ markdown, onReset }) => {
  
  // PDF Download Handler using html2pdf.js (injected in index.html)
  const handleDownloadPDF = () => {
    const element = document.getElementById('report-container');
    if (!element) return;

    const opt = {
      margin: 5,
      filename: `GoalMap_Career_Roadmap_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, backgroundColor: '#000000' }, // Capture dark theme
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // @ts-ignore - html2pdf is a global variable from CDN
    if (window.html2pdf) {
      // @ts-ignore
      window.html2pdf().set(opt).from(element).save();
    } else {
      alert('PDF Generator is loading. Please try again in a few seconds.');
    }
  };

  // Share Handler
  const handleShare = async () => {
    const shareData = {
      title: 'My Career Roadmap | GoalMap AI',
      text: 'Check out my personalized career roadmap generated by GoalMap AI! 🚀',
      url: window.location.href // Or specific app URL
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      // Fallback: Copy to clipboard
      navigator.clipboard.writeText(`${shareData.title}\n${shareData.text}\n${shareData.url}`);
      alert('Link copied to clipboard!');
    }
  };

  // WhatsApp Specific Share
  const handleWhatsAppShare = () => {
      const text = encodeURIComponent('Check out my personalized career roadmap generated by GoalMap AI! 🚀 \n' + window.location.href);
      window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  return (
    <div className="min-h-screen w-full bg-black text-white p-2 sm:p-6 relative overflow-hidden font-sans">
      
      {/* BACKGROUND LIGHTS - Green & Black Theme */}
      <div className="fixed inset-0 z-0 pointer-events-none">
         {/* Top Left Intense Green Glow */}
         <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] bg-green-600/30 rounded-full blur-[120px] animate-blob mix-blend-screen"></div>
         {/* Bottom Right Emerald Glow */}
         <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-emerald-500/20 rounded-full blur-[100px] animate-blob animation-delay-2000 mix-blend-screen"></div>
         {/* Center Light Spot */}
         <div className="absolute top-[40%] left-[50%] -translate-x-1/2 w-[40%] h-[40%] bg-green-400/10 rounded-full blur-[90px] animate-blob animation-delay-4000 mix-blend-screen"></div>
         
         {/* Subtle Ambient White Light */}
         <div className="absolute top-[10%] right-[20%] w-[30%] h-[30%] bg-white/5 rounded-full blur-[100px] animate-blob animation-delay-3000 mix-blend-overlay"></div>

         {/* Noise Texture for Gritty Feel */}
         <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-[0.07]"></div>
      </div>

      <div className="max-w-6xl mx-auto relative z-10 animate-in fade-in slide-in-from-bottom-8 duration-700">
        
        {/* Navbar Actions */}
        <div className="flex flex-col xl:flex-row justify-between items-center mb-8 gap-4 print:hidden px-2">
          <button
            onClick={onReset}
            className="group flex items-center text-green-100/70 hover:text-green-400 font-medium transition-colors w-full xl:w-auto"
          >
            <div className="p-2 rounded-full bg-black/40 group-hover:bg-green-900/30 mr-3 transition-colors border border-white/10 group-hover:border-green-500/50 backdrop-blur-md">
                 <ArrowLeft className="w-5 h-5" />
            </div>
            Back to Profile
          </button>
          
          <div className="flex flex-wrap justify-center gap-3 w-full xl:w-auto">
             <button
                onClick={handleWhatsAppShare}
                className="flex items-center px-4 py-2.5 bg-[#25D366]/20 text-[#25D366] border border-[#25D366]/30 rounded-full hover:bg-[#25D366]/30 transition-all backdrop-blur-md"
              >
                <Share2 className="w-4 h-4 mr-2" />
                WhatsApp
              </button>
             
              <button
                onClick={handleShare}
                className="flex items-center px-4 py-2.5 bg-white/10 text-white border border-white/20 rounded-full hover:bg-white/20 transition-all backdrop-blur-md"
              >
                <Share2 className="w-4 h-4 mr-2" />
                More
              </button>

              <button
                onClick={handleDownloadPDF}
                className="flex items-center px-6 py-2.5 bg-green-500/20 text-green-400 border border-green-500/30 rounded-full hover:bg-green-500/30 transition-all shadow-[0_0_15px_rgba(34,197,94,0.1)] backdrop-blur-md"
              >
                <Download className="w-4 h-4 mr-2" />
                Download PDF
              </button>
          </div>
        </div>

        {/* Report Container - DARK GLASS CARD */}
        {/* Added ID for PDF Generation */}
        <div id="report-container" className="glass-card bg-black/40 backdrop-blur-2xl p-6 sm:p-12 rounded-[2rem] shadow-[0_0_50px_rgba(0,255,100,0.05)] border border-white/10 print:shadow-none print:border-none print:p-0 print:bg-white print:text-black">
          
          {/* Header Section */}
          <div className="flex items-start gap-6 mb-12 border-b border-white/10 pb-8 print:border-black">
             <div className="p-4 bg-green-500/10 border border-green-500/40 rounded-2xl shadow-[0_0_30px_rgba(34,197,94,0.2)] print:hidden backdrop-blur-md">
                  <Target className="w-10 h-10 text-green-400" />
             </div>
             <div>
                 <h1 className="text-4xl sm:text-5xl font-extrabold text-white tracking-tight mb-2 print:text-black drop-shadow-[0_2px_10px_rgba(0,0,0,0.5)]">
                    Your Career <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-300 to-emerald-500">Strategy</span>
                 </h1>
                 <p className="text-gray-400 text-lg flex items-center gap-2 font-light print:text-gray-600">
                    <Sparkles className="w-4 h-4 text-green-500" />
                    Personalized by GoalMap AI
                 </p>
             </div>
          </div>
          
          {/* Markdown Content */}
          <div className="prose prose-invert prose-lg max-w-none 
              print:prose-headings:text-black print:prose-p:text-black print:prose-li:text-black print:prose-strong:text-black">
            <ReactMarkdown
                components={{
                    // H1
                    h1: ({node, ...props}) => (
                        <h1 {...props} className="text-3xl font-bold text-white mb-6 mt-10" />
                    ),
                    
                    // H2 - MAJOR SECTION HEADERS (Green Neon)
                    h2: ({node, ...props}) => (
                        <div className="mt-16 mb-8 group">
                            <h2 {...props} className="text-2xl sm:text-3xl font-bold text-green-400 flex items-center gap-3 uppercase tracking-wider font-sans drop-shadow-[0_0_8px_rgba(74,222,128,0.5)]" />
                            {/* Glowing Green Separator Line */}
                            <div className="h-0.5 w-full bg-gradient-to-r from-green-500 via-emerald-900/50 to-transparent mt-4 rounded-full group-hover:from-green-400 transition-all duration-500 shadow-[0_0_15px_rgba(34,197,94,0.5)]"></div>
                        </div>
                    ),

                    // H3 - SUB SECTIONS (White with Green border)
                    h3: ({node, ...props}) => (
                        <h3 {...props} className="text-xl font-semibold text-white mt-10 mb-4 flex items-center gap-3 border-l-4 border-green-500 pl-4 bg-white/5 py-2.5 rounded-r-xl shadow-[inset_0_1px_0_0_rgba(255,255,255,0.05)] backdrop-blur-sm">
                           <span className="w-1.5 h-1.5 rounded-full bg-green-400 inline-block shadow-[0_0_8px_rgba(74,222,128,0.8)]"></span>
                           {props.children}
                        </h3>
                    ),

                    // STRONG - HIGHLIGHT KEY POINTS (Green Highlight)
                    strong: ({node, ...props}) => (
                        <strong {...props} className="text-green-300 font-bold bg-green-900/30 px-1.5 py-0.5 rounded-md mx-0.5 border border-green-500/30 shadow-[0_0_10px_rgba(34,197,94,0.1)] tracking-wide" />
                    ),

                    // PARAGRAPHS
                    p: ({node, ...props}) => (
                        <p {...props} className="text-gray-300 leading-8 mb-6 text-[1.05rem] font-light tracking-wide" />
                    ),

                    // LISTS
                    ul: ({node, ...props}) => (
                        <ul {...props} className="space-y-4 my-6 pl-2" />
                    ),
                    
                    li: ({node, ...props}) => (
                        <div className="flex items-start gap-4 group">
                             <div className="mt-2 min-w-[20px] flex justify-center">
                                <div className="bg-green-500/10 p-1 rounded-full group-hover:bg-green-500/20 transition-colors border border-green-500/30">
                                    <CheckCircle2 className="w-4 h-4 text-green-400 group-hover:text-green-300 transition-colors" />
                                </div>
                             </div>
                             <li {...props} className="text-gray-300 group-hover:text-white transition-colors leading-7" />
                        </div>
                    ),

                    // BLOCKQUOTES (Notes)
                    blockquote: ({node, ...props}) => (
                        <div className="bg-green-950/30 border-l-4 border-green-500 p-6 rounded-r-xl my-8 italic text-green-200/80 shadow-[0_4px_20px_rgba(0,0,0,0.2)]">
                             <div className="flex items-center gap-2 mb-2 text-green-400 font-semibold not-italic text-sm uppercase tracking-wider">
                                <Lightbulb className="w-4 h-4" />
                                Expert Note
                             </div>
                             <blockquote {...props} className="not-italic" />
                        </div>
                    ),

                    // CODE BLOCKS (For diagrams)
                    pre: ({node, ...props}) => (
                         <div className="relative my-8 group overflow-hidden rounded-xl border border-green-500/20 bg-black shadow-2xl">
                            {/* Code Header */}
                            <div className="flex items-center px-4 py-2 bg-green-900/20 border-b border-green-500/10 gap-2">
                                <div className="w-3 h-3 rounded-full bg-red-500/50"></div>
                                <div className="w-3 h-3 rounded-full bg-yellow-500/50"></div>
                                <div className="w-3 h-3 rounded-full bg-green-500/50"></div>
                                <span className="ml-2 text-xs text-green-600/70 font-mono">pathway.mmd</span>
                            </div>
                            <pre {...props} className="p-6 overflow-x-auto text-sm font-mono text-green-300 leading-relaxed custom-scrollbar" />
                         </div>
                    ),

                    // TABLES
                    table: ({node, ...props}) => (
                        <div className="overflow-x-auto my-8 rounded-xl border border-white/10 shadow-lg bg-black/40 backdrop-blur-sm">
                            <table {...props} className="w-full text-left border-collapse" />
                        </div>
                    ),
                    thead: ({node, ...props}) => (
                        <thead {...props} className="bg-white/5 text-green-400 uppercase text-xs font-bold tracking-wider" />
                    ),
                    th: ({node, ...props}) => (
                        <th {...props} className="p-4 border-b border-white/10" />
                    ),
                    td: ({node, ...props}) => (
                        <td {...props} className="p-4 border-b border-white/5 text-gray-300 group-hover:bg-white/5 transition-colors" />
                    ),
                }}
            >
                {markdown}
            </ReactMarkdown>
          </div>

          <div className="mt-20 pt-8 border-t border-white/10 flex flex-col items-center justify-center text-center gap-2">
              <div className="w-16 h-1 bg-gradient-to-r from-green-600 to-emerald-600 rounded-full mb-4 shadow-[0_0_10px_rgba(34,197,94,0.5)]"></div>
              <div className="text-gray-500 text-sm flex items-center gap-2">
                  <span>GoalMap AI Analysis</span>
                  <span className="w-1 h-1 bg-gray-500 rounded-full"></span>
                  <span>{new Date().toLocaleDateString()}</span>
              </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportView;